name: Apron Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  C3_ENV: ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Clojure CLI
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

      - name: Install Babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run Babashka Tests (TZ=Default)
        run: bb spec

      - name: Run Babashka Tests (TZ=CST)
        run: bb spec-cst

      - name: Run Babashka Tests (TZ=MST)
        run: bb spec-mst

      - name: Run Clojure Tests (TZ=Default)
        run: clojure -M:test:spec

      - name: Run Clojure Tests (TZ=CST)
        run: clojure -M:test:spec-cst

      - name: Run Clojure Tests (TZ=MST)
        run: clojure -M:test:spec-mst

      - name: Run ClojureScript Tests (TZ=Default)
        run: clojure -M:test:cljs once

      - name: Run ClojureScript Tests (TZ=CST)
        run: |
          bb clean
          TZ=America/Chicago clojure -M:test:cljs-cst once

      - name: Run ClojureScript Tests (TZ=MST)
        run: |
          bb clean
          TZ=America/Phoenix clojure -M:test:cljs-mst once
